Repository jiweixing/cloud-ladder, pull requests merged in 2020-04, with the labels that each got.

#7 bug fixes
  examples/leap-year.cl
  src/main/antlr/CLParser.g4
  src/main/java/AST2IR.java
  src/main/java/ASTBaseListener.java
  src/main/java/ASTParser.java
  src/test/java/ASTParserTester.java
Labels: bug, enhancement

#18 feat(symtab): 增加对匿名函数的支持
  src/main/java/SymbolCheck.java
Labels: enhancement

#19 now we can test using gradle
  .gitignore
  Makefile
  build.gradle
  scripts/Makefile
  src/test/java/ASTParserTester.java
Labels: CI/CD, enhancement

#21 now CI work in full functional
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  scripts/Makefile
  settings.gradle
  src/main/antlr/CLParser.g4
  src/main/java/AST2IR.java
  src/main/java/ASTParser.java
  src/test/java/ASTParserTester.java
Labels: CI/CD

#34 fix grammar.
  .github/workflows/gradle.yml
  src/main/antlr/CLParser.g4
  src/main/java/AST2IR.java
  src/main/java/ASTParser.java
  src/main/java/IR/AssignIR.java
  src/main/java/IR/BinaryExprIR.java
  src/main/java/IR/CallExprIR.java
  src/main/java/IR/IR.java
  src/main/java/IR/IRNode.java
  src/main/java/IR/IRNodeInterface.java
  src/main/java/IR/IROperator.java
  src/main/java/IR/Label.java
  src/main/java/IR/NoOperationIR.java
  src/main/java/IR/QuadrupleNode.java
  src/main/java/IR/TripleNode.java
  src/main/java/IR/VariableDeclarationIR.java
  src/test/java/ASTParserTester.java
Labels: Compiler:AST, bug
